services:
  backend-dev:
    build:
      context: ./backend/bot
      dockerfile: ../../docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/bot:/src
      - ./backend/bot/data:/data
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/bot.db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - beerbot

  frontend-dev:
    build:
      context: ./frontend/project
      dockerfile: ../../docker/frontend/Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_BACKEND_BASE: "http://backend:8080"
      NEXT_PUBLIC_API_TOKEN: "my-secret-token"
    volumes:
      - ./frontend/project:/app/beerbot
    depends_on:
      - backend-dev
    networks:
      - beerbot

networks:
  beerbot:
    driver: bridge
